ScheduleTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ScheduleTable-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: appointmentID
        AttributeType: S
    KeySchema: 
      - AttributeName: appointmentID
        KeyType: HASH
